<a href="https://colab.research.google.com/github/fabioborges56/ProjTSP/blob/main/GradientesDescendentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
X_b = np.c_[np.ones((100, 1)), X]  # adiciona x0 = 1 a cada instância

In [25]:
theta_best = np.random.rand(100, 1)
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
theta_best

array([[3.88198841],
       [2.98591405]])

# Usando sklearn 

In [36]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
lin_reg.intercept_, lin_reg.coef_

(array([4.13182771]), array([[2.91670634]]))

In [39]:
X_new = np.array([[0], [2]])
lin_reg.predict(X_new)

array([[4.13182771],
       [9.96524038]])

# GRADIENTE DESCENDENTE EM LOTE pag. 119

In [47]:
eta = 0.5 # taxa de aprendizagem
n_iteractions = 1000
m = 100

theta = np.random.randn(2, 1)  # inicialização aleatória

In [50]:
from numpy.random.mtrand import random_integers
eta = 0.1
for iteraction in range(n_iteractions):
  gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
  theta = theta - eta * gradients
print('--------------------------------------------------------------------------------\n')
print(' --  PREVISÃO eta = 0.1 --\n')
theta

--------------------------------------------------------------------------------

 --  PREVISÃO eta = 0.1 --



array([[-1.16978645e+19],
       [ 9.99391370e+18]])

In [61]:
eta = 0.02
for iteraction in range(n_iteractions):
  gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
  theta = theta - eta * gradients
print('--------------------------------------------------------------------------------\n')
print(' --  PREVISÃO eta = 0.02 --\n')
theta

--------------------------------------------------------------------------------

 --  PREVISÃO eta = 0.02 --



array([[ 1.89966389e+130],
       [-1.62295237e+130]])

In [67]:
eta = 0.5
for iteraction in range(n_iteractions):
  gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
  theta = theta - eta * gradients
print('--------------------------------------------------------------------------------\n')
print(' --  PREVISÃO eta = 0.5 --\n')
theta

--------------------------------------------------------------------------------

 --  PREVISÃO eta = 0.5 --



array([[nan],
       [nan]])